version: "3"

services:
  db:
    image: mysql:5.6
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_DATABASE=databaseName
      - MYSQL_USER= username
      - MYSQL_PASSWORD= password
      - MYSQL_ROOT_PASSWORD= password
    volumes:
      - /data/apps/mysql:/var/lib/mysql
    restart: always
    networks:
      - default

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:lidjin
    ports:
      - "8000:8000"
      links:
      - db
