# Generated by Django 2.2.12 on 2020-05-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenicspots', '0002_active_gallery_spots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spots',
            name='businessHours',
        ),
        migrations.RemoveField(
            model_name='spots',
            name='phone',
        ),
        migrations.AlterField(
            model_name='spots',
            name='classification',
            field=models.CharField(choices=[('natural', '自然景区'), ('leisure', '人文景区')], default='natural', max_length=10, verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='spots',
            name='price',
            field=models.TextField(verbose_name='价格'),
        ),
    ]
