# Generated by Django 2.2.12 on 2020-05-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenicspots', '0003_auto_20200506_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spots',
            name='price',
            field=models.CharField(max_length=20, verbose_name='价格'),
        ),
    ]
