# Generated by Django 2.2.12 on 2020-05-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenicspots', '0004_auto_20200506_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='spots',
            name='grade',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5'), ('other', 'other')], default='other', max_length=10, verbose_name='景区级别'),
        ),
        migrations.AlterField(
            model_name='spots',
            name='address',
            field=models.CharField(max_length=50, verbose_name='景区属地'),
        ),
    ]
